[TRON]
PRIVATE_KEY = 'example'
SEED_PHRASE = 'example'
HEX_TRX = '0x891cdb91d149f23b1a45d9c5ca78a88d0cb44c18'
BASE58_TRX = 'example'
ROUTER_ADDRESS = 'TZFs5ch1R1C4mmjwrrmZqeqbUgGpxY1yWB'

[TELEGRAM]
API_ID = 'example'
API_HASH = 'example'

[REGEX]
SYMBOL_PATTERN = '\$\s*([A-Za-z]+)'
TRON_WALLET_PATTERN = 'T[1-9A-HJ-NP-Za-km-z]{33}'
SOLANA_WALLET_PATTERN = '[1-9A-HJ-NP-Za-km-z]{32,44}'