[TELEGRAM]
API_ID = 29131368
API_HASH = '4bc83f41154e6092e4fc2aaa3be82f97'
PRIVATE_KEY = '0xc'

[REGEX]
SYMBOL_PATTERN = '\$\s*([A-Za-z]+)'
TRON_WALLET_PATTERN = 'T[1-9A-HJ-NP-Za-km-z]{33}'
SOLANA_WALLET_PATTERN = '[1-9A-HJ-NP-Za-km-z]{32,44}'